export const initialStateCompany = {
    isActive: null,
    isDeleted: null,
    code: null,
    name: '',
    address: '',
    bussinessName: '',
    updatedAt: null,
    createdAt: null,
    createdAmountAt: null,
    createdAmountUserId: null,
    createdAmountUser: null,
    paymentPeriodicityRef: null,
    hiddenFields: null,
    customerRef: null,
    paymentTypeRef: null,
    numberOfPeriod: '',
    paysheetProcessDuration: '',
    ExposureDays: '',
    porcentageAdvanceAccrued: '',
    porcentageAdvanceNoAccrued: '',
    deadlinePay: '',
    cutDate: '',
    cutDayOne: '',
    cutDayPost: '',
    cutDayRef: null,
    isDispersion: false,
    officialIdentification: false,
    digitalSignature: false,
    CURP: false,
    proofAddress: false,
    CLABE: false,
    extraField: [],
    emailNotification: []

}

export const initialStateCompanyError = {
    name: false,
    code: false,
    customerRef: false,
    paymentPeriodicityRef: false,
    hiddenFields: false,
    paymentTypeRef: false,
    numberOfPeriod: false,
    paysheetProcessDuration: false,
    ExposureDays: false,
    porcentageAdvanceAccrued: false,
    porcentageAdvanceNoAccrued: false,
    creditLine: false,
    deadlinePay: false,
    address: false,
    businessName: false,
    cutDate: false,
    cutDayOne: false,
    cutDayPost: false,
    cutDayRef: false,

}